// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 11/19/2024, 5:17:51 PM
const configMerger = require("D:/Homefood/home-food-HO1-T5-user-edit-profile/home-food-HO1-T5-user-edit-profile/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: { files: ["D:/Homefood/home-food-HO1-T5-user-edit-profile/home-food-HO1-T5-user-edit-profile/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Homefood/home-food-HO1-T5-user-edit-profile/home-food-HO1-T5-user-edit-profile/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Homefood/home-food-HO1-T5-user-edit-profile/home-food-HO1-T5-user-edit-profile/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Homefood/home-food-HO1-T5-user-edit-profile/home-food-HO1-T5-user-edit-profile/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Homefood/home-food-HO1-T5-user-edit-profile/home-food-HO1-T5-user-edit-profile/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Homefood/home-food-HO1-T5-user-edit-profile/home-food-HO1-T5-user-edit-profile/plugins/**/*.{js,ts,mjs}","D:/Homefood/home-food-HO1-T5-user-edit-profile/home-food-HO1-T5-user-edit-profile/composables/**/*.{js,ts,mjs}","D:/Homefood/home-food-HO1-T5-user-edit-profile/home-food-HO1-T5-user-edit-profile/utils/**/*.{js,ts,mjs}","D:/Homefood/home-food-HO1-T5-user-edit-profile/home-food-HO1-T5-user-edit-profile/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/Homefood/home-food-HO1-T5-user-edit-profile/home-food-HO1-T5-user-edit-profile/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/Homefood/home-food-HO1-T5-user-edit-profile/home-food-HO1-T5-user-edit-profile/app.config.{js,ts,mjs}"] } }));

module.exports = config
