// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 21/11/2024, 10:11:47
const configMerger = require("/Users/sirawitkumlungsri/Documents/GitHub/home-food/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: { files: ["/Users/sirawitkumlungsri/Documents/GitHub/home-food/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/sirawitkumlungsri/Documents/GitHub/home-food/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/sirawitkumlungsri/Documents/GitHub/home-food/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/sirawitkumlungsri/Documents/GitHub/home-food/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/sirawitkumlungsri/Documents/GitHub/home-food/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/sirawitkumlungsri/Documents/GitHub/home-food/plugins/**/*.{js,ts,mjs}","/Users/sirawitkumlungsri/Documents/GitHub/home-food/composables/**/*.{js,ts,mjs}","/Users/sirawitkumlungsri/Documents/GitHub/home-food/utils/**/*.{js,ts,mjs}","/Users/sirawitkumlungsri/Documents/GitHub/home-food/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/sirawitkumlungsri/Documents/GitHub/home-food/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/sirawitkumlungsri/Documents/GitHub/home-food/app.config.{js,ts,mjs}"] } }));

module.exports = config
